address: https://test-stand.gb.ru
browser: chrome
sleep: 1
implicitly_wait: 3
login: "Ivan33"
pass: "102dc62c67"
title: "Auto Create Post From Selenium"
description: "WOW! Magic!"
contest: "Its fun"
email: "wow@gmail.com"
message: "Test message"


